### ISSUE TITLE
Blender 4.1.1 linux - Installation

### ISSUE THREAD

**Issue by chlowden** [panzi/blender-addon-import-pixelart#1]
Hello
I am struggling to install your plugin on  Blender 4.1.1 linux. Do you know if your plugin is compatible? Thank you

**Comment by panzi** [comment]
Oh I haven't tried it on a recent blender release. *If* I have time I'll check next weekend.

**Comment by chlowden** [comment]
Ok. Thank you very much.

⁣Get BlueMail for Android ​

**Comment by chlowden** [comment]
Hello, Were you able to take a look at this please?
Thank you

**Comment by panzi** [comment]
Ok, I tried it now with Blender 4.1.1 and it works for me. What exactly does not work for you? At what step what error does occur? If you open the scripting tab what do you see in the log view on the bottom left? And after installing the add-on, did you enable it? There's a checkbox left of "Import-Export: Import Pixel Art".

**Comment by chlowden** [comment]
I'm sorry that I bothered you. The plugin was crashing on all the pngs I
was using, but I've just realized that all my pngs were much larger than
1x1. I found a tiny png icon and it all works.
Now I have to get my head round how to reduce my large pngs down to the 1x1
pixel ratio.
Sorry again.
Thank you for a great plugin.

**Comment by chlowden** [comment]
Maybe you may want to add a brief explanation on how to reduce pngs down to
a 1:1 pixel ratio using a custom grid in gimp.
https://www.youtube.com/watch?v=GQz3hdAZEHk
Note that the gimp scale tool should have interpolation turned off.

**Comment by panzi** [comment]
Because I too had the issue that these days all pixel art that you can find online is up-scaled I've added an option for automatic down-scaling. It tries to detect how the image was up-scaled and then down-scales if before further processing. But it's all a Python script of course, so it might be really slow. Anyway, would like to know if that would have worked with the images you where trying to import. :smile:
